--TASK 1 
SELECT *, ROW_NUMBER() OVER(ORDER BY SaleDate) AS RowNum
FROM ProductSales
--TASK 2 
WITH CTE AS(
SELECT *,
SUM(Quantity) OVER(PARTITION BY ProductName) Total
FROM ProductSales
)
SELECT *,
DENSE_RANK() OVER(ORDER BY Total DESC) Ranking
FROM CTE
--TASK 3 
WITH CTE AS (
SELECT *,
ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY SaleAmount DESC) AS RN
FROM ProductSales
)
SELECT * FROM CTE
WHERE RN = 1
--TASK 4 
SELECT SaleDate, SaleAmount,
LEAD(SaleAmount) OVER (ORDER BY SALEDATE) AS NextSaleAmount
FROM ProductSales
--TASK 5 
SELECT SaleDate, SaleAmount,
LAG(SALEAMOUNT) OVER(ORDER BY SALEDATE) AS PreviousSaleAmount
FROM ProductSales
--TASK 6 
WITH CTE AS(
SELECT SaleDate, SaleAmount,
LAG(SALEAMOUNT) OVER(ORDER BY SALEDATE) AS PreviousSaleAmount
FROM ProductSales
)
SELECT * FROM CTE 
WHERE SALEAMOUNT > PREVIOUSSALEAMOUNT
--TASK 7 
SELECT SALEID, PRODUCTNAME, SALEDATE, SALEAMOUNT,
SALEAMOUNT-LAG(SALEAMOUNT) OVER(PARTITION BY PRODUCTNAME ORDER BY SALEDATE)AS DIFFPREV
FROM PRODUCTSALES

--TASK 8 
SELECT SaleID, ProductName, SaleDate, SaleAmount,
(LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE)-SaleAmount)/SaleAmount*100 AS PercentChange
FROM ProductSales
--TASK 9 
SELECT ProductName, SaleDate, SaleAmount,
SALEAMOUNT/LAG(SALEAMOUNT) OVER(PARTITION BY PRODUCTNAME ORDER BY SALEDATE) AS RATIO
FROM ProductSales
--TASK 10 
SELECT ProductName, SaleDate, SaleAmount,
SALEAMOUNT - FIRST_VALUE(SaleAmount) OVER (PARTITION BY PRODUCTNAME ORDER BY SALEDATE) DIFF
FROM ProductSales
--TASK 11 
WITH CTE AS(
SELECT ProductName, SaleDate, SaleAmount,
LAG(SALEAMOUNT) OVER(PARTITION BY PRODUCTNAME ORDER BY SALEDATE) AS PR
FROM ProductSales
)
SELECT * FROM CTE 
WHERE SALEAMOUNT > PR
--TASK 12
SELECT SaleID, ProductName, SaleAmount,
       SUM(SaleAmount) OVER (ORDER BY SaleDate) AS RunningTotal
FROM ProductSales;
--TASK 13 
Select *,
AVG(SALEAMOUNT) OVER(ORDER BY SALEDATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AVG
FROM ProductSales
--TASK 14
SELECT *,
SALEAMOUNT-AVG(SALEAMOUNT) OVER() DIFF
FROM ProductSales

--TASK 15
WITH CTE AS(
SELECT EmployeeID, Name, Salary,
       DENSE_RANK() OVER (ORDER BY Salary DESC) AS SalaryRank
FROM Employees1
)
SELECT * FROM CTE
WHERE SalaryRANK IN(
SELECT SALARYRANK FROM CTE
GROUP BY SalaryRank
HAVING COUNT(*) >1
)

--TASK 16
WITH CTE AS(
SELECT *,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) RN
FROM Employees1
)
SELECT * FROM CTE
WHERE RN <=2
--TASK 17
WITH CTE AS(
SELECT *,
MIN(SALARY) OVER(PARTITION BY DEPARTMENT) MINS
FROM Employees1
)
SELECT EmployeeID, Name, Department, Salary
FROM CTE
WHERE SALARY = MINS
--TASK 18
SELECT *,
SUM(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) TOTAL
FROM EMPLOYEES1
--TASK 19
SELECT DISTINCT DEPARTMENT,
SUM(SALARY) OVER(PARTITION BY DEPARTMENT) TOTAL
FROM Employees1
--TASK 20
SELECT DISTINCT DEPARTMENT,
AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AVG
FROM EMPLOYEES1 
--TASK 21
SELECT*,
SALARY-AVG(SALARY) OVER(PARTITION BY DEPARTMENT) DIFF
FROM  EMPLOYEES1 
--TASK 22
SELECT *,
AVG(SALARY) OVER(ORDER BY EMPLOYEEID ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AVG
FROM EMPLOYEES1 
--TASK 23
WITH CTE AS(
SELECT *,
DENSE_RANK() OVER(ORDER BY HIREDATE DESC) DR
FROM EMPLOYEES1
)
SELECT *,
SUM(SALARY) OVER()
FROM CTE 
WHERE DR <=3
